### ISSUE TITLE
check for a better install solution

### ISSUE THREAD

**Issue by alexraileanu** [opper/jump#5]
right now the install.sh script clones the repo, creates a virtualenv and installs requirements but i feel like there must be a better way of doing this. especially since for the jumpgate to work, there needs to be a .env file with some values populated in it.

**Comment by Nhoya** [comment]
From where you can pick those values? we can create a dummy .env file and move it in the right spot, but stll we need to get the variables values

**Comment by alexraileanu** [comment]
yeah that i don't know for sure. do you know of any online json mocker service? because that way we can populate the .env file with some dummy data from that service indeed.

**Comment by Nhoya** [comment]
And what if the server is down? I don't think that's the right solution, we can jus hardcode what we need or use stuff like jq, but can you give me an example of what you really need? the instructions are unclear

**Comment by alexraileanu** [comment]
sorry for not being too clear! in the end what i would need is (ideally without changing the source code) a JSON response that fits the example given in the readme file. 

the way it works now is that a request is made to an endpoint (stored in the .env file) which then returns the list of items to build the menu. and i figured that an online mocker would work because it would fit exactly this need but you are right, it could be that the service goes offline without noticing.

**Comment by Nhoya** [comment]
Can you show me an example of the json file? Another thing, what's the issue in hardcoding it?

**Comment by alexraileanu** [comment]
@Nhoya i just realised i didn't merge the pr that added the example. sorry! 

```
{
    "items": [
        {
            "id": "b84b07c8-738e-4088-969f-0ee4c822fd3a",
            "in_jumpgate": false,
            "name": "test-app",
            "servers": [
                {
                    "display_name": "Staging",
                    "id": "939bf2ce-d0e0-42b8-8600-f7f7ef5db72b",
                    "ip": "1.2.3.4",
                    "is_serverpilot": true,
                    "name": "staging",
                    "port": 222,
                    "user": "serverpilot"
                },
                {
                    "display_name": "Production",
                    "id": "6a7f9169-5fe3-49d2-8eea-bfafcc53f4de",
                    "ip": "1.2.3.4",
                    "is_serverpilot": false,
                    "name": "prod",
                    "port": 222,
                    "user": "root"
                }
            ]
        }, {
            "id": "81a1afa3-f610-4b64-935f-7e93c025209b",
            "in_jumpgate": true,
            "last_backup": 1538352010,
            "name": "another-test-app",
            "servers": [
                {
                    "created_at": 1533644177,
                    "display_name": "Staging",
                    "id": "939bf2ce-d0e0-42b8-8600-f7f7ef5db72b",
                    "ip": "1.2.3.4",
                    "is_serverpilot": true,
                    "name": "staging",
                    "port": 222,
                    "updated_at": 1533808205,
                    "user": "serverpilot"
                }, {
                     "created_at": 1533644177,
                     "display_name": "Acceptance",
                     "id": "939bf2ce-d0e0-42b8-8600-f7f7ef5db72b",
                     "ip": "1.2.3.4",
                     "is_serverpilot": true,
                     "name": "acceptance",
                     "port": 222,
                     "updated_at": 1533808205,
                     "user": "serverpilot"
                 }
            ]
        }
    ]
}
```

here's an example.

and i'm not quite sure i understand then what do you mean by hardcoding. hardcoding what and where?
